version: "3"

services:
  app:
    container_name: dz-cloud-service-messager
    build: .
    ports:
      - '127.0.0.1:3000:3000'
    restart: always
  mongo:
    image: mongo:latest
    container_name: dz-messages-database
    volumes:
      - db:/data/db
    ports:
      - '27027:27017'
    restart: always

volumes:
  db:
